Cloud-init v. 22.4.2 running 'init-local' at Fri, 12 Sep 2025 00:11:46 +0000. Up 12.67 seconds.
2025-09-12 00:11:46,747 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'> failed
Cloud-init v. 22.4.2 running 'init' at Fri, 12 Sep 2025 00:11:48 +0000. Up 15.00 seconds.
ci-info: +++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++
ci-info: +--------+-------+-----------+-----------+-------+-------------------+
ci-info: | Device |   Up  |  Address  |    Mask   | Scope |     Hw-Address    |
ci-info: +--------+-------+-----------+-----------+-------+-------------------+
ci-info: |  eth0  | False |     .     |     .     |   .   | b8:27:eb:65:09:fc |
ci-info: |   lo   |  True | 127.0.0.1 | 255.0.0.0 |  host |         .         |
ci-info: |   lo   |  True |  ::1/128  |     .     |  host |         .         |
ci-info: | wlan0  | False |     .     |     .     |   .   | b8:27:eb:30:5c:a9 |
ci-info: +--------+-------+-----------+-----------+-------+-------------------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: +-------+-------------+---------+-----------+-------+
2025-09-12 00:11:49,775 - util.py[WARNING]: Running interface command ['nmcli', 'connection', 'load', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] failed
2025-09-12 00:11:49,808 - util.py[WARNING]: Running interface command ['nmcli', 'connection', 'reload'] failed
2025-09-12 00:11:49,838 - util.py[WARNING]: Running interface command ['nmcli', 'connection', 'up', 'ifname', 'eth0'] failed
2025-09-12 00:11:49,995 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
Cloud-init v. 22.4.2 running 'modules:config' at Fri, 12 Sep 2025 00:12:02 +0000. Up 28.38 seconds.
